
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bootdb?createDatabaseIfNotExist=true&autoReconnect=true&useSSL=false
    username: root
    password: jorge
    platform: mysql
  jpa:
    hibernate:
    ddl-auto: create
    generate-ddl: true